name: doc

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'requirements.dev.txt'
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: npm install
      run: |
        npm install -g @2fd/graphdoc
    - name: pip install
      run: |
        pip install -r requirements.txt
    - name: git init
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: generate document
      run: |
        make docs
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
    - uses: actions/upload-artifact@v3
      with:
        name: schema
        path: |
          schema.json
          schema.graphql


