name: doc

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'requirements.dev.txt'
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.13.1'
    - name: go install
      run: |
        go install github.com/Code-Hex/gqldoc/cmd/gqldoc@latest
    - name: npm install
      run: |
        npm install -g @2fd/graphdoc
    - name: pip install
      run: |
        pip install -r requirements.txt
    - name: git init
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: generate document
      run: |
        make doc
    - name: check doc
      run: |
        git diff --exit-code --name-only
      continue-on-error: true
    - name: push doc
      run: |
        git add .
        git commit -m "update docs"
        git push origin main
